Reverse proxy
browserstack/requests-debugger pull request #6
Opened 2020-10-12 05:36 UTC by neerajshukla1911

2020-10-12 08:15 UTC, rchougule requested changes
Majority of the code in `reverseProxy.js` is common with `proxy.js`. Possible to take out the common part in a base class/file?

2020-10-12 16:01 UTC, Archish27 commented on config/constants.js
>  module.exports.HUB_STATUS_URL = 'http://hub-cloud.browserstack.com/wd/hub/status';
can we utilise constant `HUB_HOST` in `HUB_STATUS_URL`?

2020-10-12 16:01 UTC, Archish27 commented on test/reverseProxy.test.js
> +var REVERSE_PROXY_DOMAIN = `http://127.0.0.1:${RdGlobalConfig.RD_HANDLER_REVERSE_PROXY_PORT}`;
Constant?

2020-10-12 16:01 UTC, Archish27 commented on test/reverseProxy.test.js
> +var HUB_STATUS_URI_PATH = "/wd/hub/status";
Can we utilize this from constants? Or create a new constant?

2020-10-14 11:54 UTC, Archish27 commented on src/requestLib.js
> +              message: err,
Can this be moved to function? Duplicates with `https`?

2020-10-16 08:57 UTC, rchougule commented on src/commandLine.js
> +
whitespace...

2020-10-16 08:58 UTC, rchougule commented on src/commandLine.js
> +
and at other places as well..

2020-10-16 09:00 UTC, rchougule commented on src/requestLib.js
> +      var request = null;
can be moved back to line 29...

2020-10-16 09:01 UTC, rchougule commented on src/requestLib.js
> +      keepAliveAgent = new schemeObj.Agent({keepAlive: true});
no need to create the agent again and again... can be selected conditionally wherever required...

2020-10-16 09:03 UTC, rchougule commented on src/requestLib.js
> +      };
why do we need to do this?...

2020-10-16 09:05 UTC, rchougule commented on src/server.js
> +
Please use the eslint config. Can be setup in the respective IDE for these...

2020-10-16 09:05 UTC, rchougule commented on src/server.js
> +     * doesn't exists
comment seems broken...

2020-10-16 16:23 UTC, closed without merging

2020-10-16 16:24 UTC, neerajshukla1911 commented
Raised another PR with https support